import type { GitHubIssueDetail, MissionReference, RepositoryData, RepositorySnapshot, TrackedIssueSummary } from '@flying-pillow/mission-core/entities/Repository/RepositorySchema';
import type { AgentSessionSnapshot, AgentSessionTerminalSnapshot } from '@flying-pillow/mission-core/entities/AgentSession/AgentSessionSchema';
import type { MissionSnapshot, MissionTerminalSnapshot } from '@flying-pillow/mission-core/entities/Mission/MissionSchema';
import type { GitHubVisibleRepositorySummary as CoreGitHubVisibleRepositorySummary } from '@flying-pillow/mission-core/entities/GitHubRepository/GitHubRepositorySchema';
import type { MissionStageId, MissionTowerTreeNode, OperatorActionDescriptor, OperatorActionExecutionStep, OperatorActionFlowStep, OperatorActionListSnapshot, OperatorActionQueryContext, OperatorActionTargetContext, OperatorStatus } from '@flying-pillow/mission-core/types';
import type { AirportRuntimeEventEnvelope } from "$lib/contracts/runtime-events";

export type RepositorySummary = RepositoryData;
export type GitHubVisibleRepositorySummary = CoreGitHubVisibleRepositorySummary;
export type MissionSummary = MissionReference;
export type SidebarRepositorySummary = RepositorySummary & {
    id: string;
    missions?: MissionSummary[];
};
export type AirportRepositoryListItem = {
    key: string;
    local?: SidebarRepositorySummary;
    github?: GitHubVisibleRepositorySummary;
    displayName: string;
    displayDescription: string;
    repositoryRootPath?: string;
    githubRepository?: string;
    missions: MissionSummary[];
    isLocal: boolean;
};
export type IssueSummary = TrackedIssueSummary;
export type MissionSessionSummary = AgentSessionSnapshot;
export type SelectedMissionSummary = MissionSnapshot;
export type SelectedIssueSummary = GitHubIssueDetail;
export type RepositorySnapshotData = RepositorySnapshot;
export type MissionRuntimeEventEnvelope = AirportRuntimeEventEnvelope;
export type MissionSessionTerminalSnapshotData = AgentSessionTerminalSnapshot;
export type MissionTerminalSnapshotData = MissionTerminalSnapshot;
export type MissionStageIdData = MissionStageId;
export type MissionTowerTreeNodeData = MissionTowerTreeNode;
export type OperatorActionDescriptorData = OperatorActionDescriptor;
export type OperatorActionExecutionStepData = OperatorActionExecutionStep;
export type OperatorActionFlowStepData = OperatorActionFlowStep;
export type OperatorActionListSnapshotData = OperatorActionListSnapshot;
export type OperatorActionQueryContextData = OperatorActionQueryContext;
export type OperatorActionTargetContextData = OperatorActionTargetContext;
export type OperatorStatusData = OperatorStatus;
